feat: add workflow to build docker container and trigger deployment to aws nonprod envs (#1)
* Start by copying in what is working for flowcode-generator-server

* Trigger via workflow_call and accept service_name as input

* WIP

* Add steps to update values.yaml and open a PR

* Use service_name and team_name, and rename file to match workflow name

* Need to explicitly define secrets again

* Don't need the type: string

* Provide the special github token

To prevent this error:
Error: buildx failed with: error: failed to solve: failed to read dockerfile: failed to update submodules for https://github.com/dtx-company/flowcode-generator-server.git: exit status 1

* Use yq action and rename personal access token

* Abstract IMAGE_TAG into env variable

* Reference fro env

* Remove bad quotes

* Simpler names for inputs

* Add caching to docker build and push action

Trying to follow https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api

* Go back to old way of installing yq

Otherwise, am getting:
Error: unknown command ".fc-service.process.tag = 25" for "yq"

* Push to trunk directly for nonprod

* Remove unneeded log and add a comment